version: "3"

services:
  exporter:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: /bin/bash -c "go run ./cmd/brigade-exporter/* --debug --development --fake"
    volumes:
      - ../../:/go/src/github.com/slok/brigade-exporter
    ports:
      - 9480

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports: 
      - 9090:9090