global:
  scrape_interval: 10s

scrape_configs:
  - job_name: brigade
    scrape_interval: 10s
    static_configs:
      - targets: ["exporter:9480"]
        labels:
          mode: fake
          environment: dev
